name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'
      - name: Run linters and tests
        run: |
          go install github.com/mgechev/revive@latest
          test -z $(gofmt -l .)
          revive -set_exit_status ./...
          go vet ./...
          go test -v ./...
